# CMake generated Testfile for 
# Source directory: /home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests
# Build directory: /home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/build-verify/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_config "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/build-verify/tests/test_config")
set_tests_properties(test_config PROPERTIES  _BACKTRACE_TRIPLES "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;6;add_test;/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;0;")
add_test(test_rate_limiter "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/build-verify/tests/test_rate_limiter")
set_tests_properties(test_rate_limiter PROPERTIES  _BACKTRACE_TRIPLES "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;15;add_test;/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;0;")
add_test(test_audit_log "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/build-verify/tests/test_audit_log")
set_tests_properties(test_audit_log PROPERTIES  _BACKTRACE_TRIPLES "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;25;add_test;/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;0;")
add_test(test_client_context "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/build-verify/tests/test_client_context")
set_tests_properties(test_client_context PROPERTIES  _BACKTRACE_TRIPLES "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;35;add_test;/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;0;")
add_test(test_secret_store "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/build-verify/tests/test_secret_store")
set_tests_properties(test_secret_store PROPERTIES  _BACKTRACE_TRIPLES "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;44;add_test;/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;0;")
add_test(test_nss_openbastion "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/build-verify/tests/test_nss_openbastion")
set_tests_properties(test_nss_openbastion PROPERTIES  _BACKTRACE_TRIPLES "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;49;add_test;/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;0;")
add_test(test_nss_cache "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/build-verify/tests/test_nss_cache")
set_tests_properties(test_nss_cache PROPERTIES  _BACKTRACE_TRIPLES "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;65;add_test;/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;0;")
add_test(test_path_validator "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/build-verify/tests/test_path_validator")
set_tests_properties(test_path_validator PROPERTIES  _BACKTRACE_TRIPLES "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;70;add_test;/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;0;")
add_test(test_username_validator "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/build-verify/tests/test_username_validator")
set_tests_properties(test_username_validator PROPERTIES  _BACKTRACE_TRIPLES "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;75;add_test;/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;0;")
add_test(test_ob_cert_proto "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/build-verify/tests/test_ob_cert_proto")
set_tests_properties(test_ob_cert_proto PROPERTIES  _BACKTRACE_TRIPLES "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;80;add_test;/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;0;")
add_test(test_ob_client "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/build-verify/tests/test_ob_client")
set_tests_properties(test_ob_client PROPERTIES  _BACKTRACE_TRIPLES "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;96;add_test;/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;0;")
add_test(test_auth_cache "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/build-verify/tests/test_auth_cache")
set_tests_properties(test_auth_cache PROPERTIES  _BACKTRACE_TRIPLES "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;109;add_test;/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;0;")
add_test(test_token_manager "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/build-verify/tests/test_token_manager")
set_tests_properties(test_token_manager PROPERTIES  _BACKTRACE_TRIPLES "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;168;add_test;/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;0;")
add_test(test_crowdsec "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/build-verify/tests/test_crowdsec")
set_tests_properties(test_crowdsec PROPERTIES  _BACKTRACE_TRIPLES "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;184;add_test;/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;0;")
add_test(test_service_account "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/build-verify/tests/test_service_account")
set_tests_properties(test_service_account PROPERTIES  _BACKTRACE_TRIPLES "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;189;add_test;/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;0;")
add_test(test_token_cache "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/build-verify/tests/test_token_cache")
set_tests_properties(test_token_cache PROPERTIES  _BACKTRACE_TRIPLES "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;202;add_test;/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;0;")
add_test(test_token_manager_io "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/build-verify/tests/test_token_manager_io")
set_tests_properties(test_token_manager_io PROPERTIES  _BACKTRACE_TRIPLES "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;217;add_test;/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;0;")
add_test(test_notify "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/build-verify/tests/test_notify")
set_tests_properties(test_notify PROPERTIES  _BACKTRACE_TRIPLES "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;233;add_test;/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;0;")
add_test(test_ssh_key_policy "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/build-verify/tests/test_ssh_key_policy")
set_tests_properties(test_ssh_key_policy PROPERTIES  _BACKTRACE_TRIPLES "/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;238;add_test;/home/yadd/dev/github/open-bastion/.claude/worktrees/agent-ae9d6acf802117205/tests/CMakeLists.txt;0;")
